name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - accelerate
  - beautifulsoup4
  - numpy
  - pandas
  - pgvector
  - pip
  - psycopg2
  - pyodbc
  - pypdf
  - pytorch
  - pytorch-lightning
  - redis-py
  - sentence-transformers
  - torchmetrics
  - torchvision
  - transformers
  - unixodbc
  - pip:
      - langchain
      - langchain-community
      - langchain-core
      - langchain-elasticsearch
      - langchain-huggingface
      - langchain-sqlserver
      - langchain-text-splitters
